feat. CyberPaymaster
cyberconnecthq/cybergraph pull request #6
Opened 2023-12-12 08:12 UTC by PengDeng-Cyber

2023-12-12 19:55 UTC, ZhimaoL requested changes

2023-12-12 19:55 UTC, ZhimaoL commented on src/paymaster/CyberPaymaster.sol
> +    uint256 private constant POST_OP_OVERHEAD = 34982;
这个overhead要做成可modify的么？这样这个paymaster脱离了BASE在其他链上我们也可以用？
in general, 我在想把这个pm实现往generic pm靠会有多复杂，不复杂的话做generic一点之后可以直接部署在其他链上以后

2023-12-13 02:02 UTC, PengDeng-Cyber commented on src/paymaster/CyberPaymaster.sol
> +    uint256 private constant POST_OP_OVERHEAD = 34982;
感觉不用， 现在只有设置了 `metaPaymaster` 才会走postOp，所以这个pm也可以直接在其他链上用，不设置 `metaPaymaster` 就行了。

2023-12-13 02:16 UTC, PengDeng-Cyber commented on src/paymaster/CyberPaymaster.sol
> +    uint256 private constant POST_OP_OVERHEAD = 34982;
其他链不会有`metaPaymaster ` 所以overhead也用不到

2024-01-08 05:52 UTC, merged