launch bridge
cyberconnecthq/cybergraph pull request #8
Opened 2024-02-22 08:55 UTC by PengDeng-Cyber

2024-02-22 22:55 UTC, ZhimaoL requested changes

2024-02-22 22:55 UTC, ZhimaoL commented on src/periphery/LaunchBridge.sol
> +contract LaunchBridge is
It has nothing to do with bridge, change the name

2024-02-22 22:55 UTC, ZhimaoL commented on src/periphery/LaunchBridge.sol
> +import { Initializable } from "openzeppelin-contracts/contracts/proxy/utils/Initializable.sol";
Let's make this contract non-upgradable.

2024-02-22 22:55 UTC, ZhimaoL commented on src/periphery/LaunchBridge.sol
> +    function withdraw(address to, uint256 amount) external onlyOwner {
Should we allow for the withdrawal of noncyber tokens? e,g, native ETH or other ERC-20 was sent to this contract accidentally.

2024-02-22 23:13 UTC, ZhimaoL commented on src/periphery/LaunchBridge.sol
> +contract LaunchBridge is
e.g.
TokenPool

2024-02-23 03:43 UTC, PengDeng-Cyber commented on src/periphery/LaunchBridge.sol
> +    function withdraw(address to, uint256 amount) external onlyOwner {
transferring native token a contract with no `receive()` or `fallback() payable` defined will revert on evm.
And we can add erc-20 functions

2024-02-23 21:45 UTC, ZhimaoL approved these changes

2024-02-23 21:45 UTC, merged